version: '2'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: bash runserver.sh
    volumes:
      - .:/code
    ports:
      - "8080:5000"
    depends_on:
      - db
  db:
    #image: mongo
    build:
        context: .
        dockerfile: Dockerfile-mongo
    volumes:
      - playbill-db:/data/db

volumes:
  playbill-db:
    external: true
